name: uoc20251pec1
channels:
  - defaults
  - conda-forge
dependencies:
  - imbalanced-learn=0.14.0
  - jupyter=1.1.1
  - matplotlib=3.10.0
  - numpy=2.2.3
  - pandas=2.2.3
  - python=3.13.2
  - scikit-learn=1.6.1
  - seaborn=0.13.2